// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Courses struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Desc    string `json:"desc"`
	MajorID int32  `json:"major_id"`
}

type Majors struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Desc  string `json:"desc"`
}

type Users struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
