// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password,
    role
) VALUES (
    'admin',
    'password',
    'admin'
) RETURNING id, username, password, role, created_at
`

func (q *Queries) CreateUser(ctx context.Context) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
